In [21]:
%matplotlib inline
import matplotlib as plt
import pandas as pd
import numpy as np
import plotly.express as px
from plotly.tools import mpl_to_plotly
import plotly.graph_objects as go

In [19]:
calls = pd.read_csv(r"C:/Users/btros/Detroit-911-Calls-Dash-App/notebooks/raw_csvs/call_grid_with_weather.csv")
holidays = pd.read_csv(r"C:/Users/btros/Detroit-911-Calls-Dash-App/notebooks/raw_csvs/holidays.csv")
calls_raw = pd.read_csv(r"C:/Users/btross/OneDrive/Documents/LSDS-Unit-2-Project/911_Calls_For_Service.csv")
holidays = holidays.drop(columns='Unnamed: 0')
calls = calls.drop(columns='Unnamed: 0')

In [16]:
merged = pd.merge(calls, holidays, how='left', on=
                  ['year', 'month', 'day'])

In [13]:
merged = merged.drop(columns='Unnamed: 0')

In [20]:
merged['is_holiday'] = merged['is_holiday'].replace(np.NaN, 0)
merged

,year,month,day,dow,week,part_of_day,lat_grid,lon_grid,count,weather_id,severe,temp_min,temp_max,is_holiday
0,2016,9,20,1,38,1,5.0,3.0,1,800.5,0.0,61.661,70.169,0.0
1,2016,9,20,1,38,1,5.0,4.0,1,800.5,0.0,61.661,70.169,0.0
2,2016,9,20,1,38,1,5.0,9.0,1,800.5,0.0,61.661,70.169,0.0
3,2016,9,20,1,38,1,7.0,3.0,1,800.5,0.0,61.661,70.169,0.0
4,2016,9,20,1,38,1,7.0,11.0,1,800.5,0.0,61.661,70.169,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392107,2019,11,14,3,46,4,9.0,9.0,1,753.0,0.0,23.450,27.050,0.0
392108,2019,11,14,3,46,4,9.0,10.0,3,753.0,0.0,23.450,27.050,0.0
392109,2019,11,14,3,46,4,9.0,11.0,4,753.0,0.0,23.450,27.050,0.0
392110,2019,11,14,3,46,4,9.0,12.0,16,753.0,0.0,23.450,27.050,0.0
392111,2019,11,14,3,46,4,9.0,13.0,2,753.0,0.0,23.450,27.050,0.0

In [27]:
px.density_heatmap(merged, x='lon_grid', y='lat_grid')